[package]
name = "rust_a_star"
version = "0.0.1"
authors = ["Jared McFarland <jared.online@gmail.com>"]
build = "build.rs"

[lib]
name = "rust_a_star"
crate-type = ["dylib"]

[dependencies]
lazy_static = "0.1.*"
